### ISSUE TITLE
onit install not completing due to error

### ISSUE THREAD

**Issue by KramKroc** [onosproject/onos-test#162]
I'm running the following command to install `onit`:

```
go get github.com/onosproject/onos-test/cmd/onit
```

which results in the following output:

```
go: finding github.com/onosproject/onos-test latest
# github.com/onosproject/onos-test/test/env
../../../../pkg/mod/github.com/onosproject/onos-test@v0.0.0-20191126082912-6830441dd0e1/test/env/env.go:191:42: undefined: "github.com/onosproject/onos-config/pkg/northbound/admin".ConfigAdminServiceClient
../../../../pkg/mod/github.com/onosproject/onos-test@v0.0.0-20191126082912-6830441dd0e1/test/env/env.go:200:15: undefined: "github.com/onosproject/onos-config/pkg/northbound/admin".NewConfigAdminServiceClient
```

which indicates the install fails. Attempting to run the command shows this to be the case:

```
$ onit
zsh: command not found: onit
```

**Comment by Andrea-Campanella** [comment]
@KramKroc are you issuing this command in the `onos-config` folder or in `~`?

**Comment by KramKroc** [comment]
@Andrea-Campanella in onos-config AFAIR. I've since pulled down the onos-test code and used that to generate the binary.

**Comment by KramKroc** [comment]
@Andrea-Campanella I ran it from my onos-config work space, e.g. 

```
~/go/src/github.com/onosproject/onos-config
```

I changed to the home directory and ran it again, i.e. from `~` and the command worked.

**Comment by Andrea-Campanella** [comment]
@KramKroc yes, unfortunately working form the `onos-config` folder is broken due to `go.mod` differences. We are in the process of doing the second iteration of `onit` to overcome some of the issues we had with this version, namely not being capable of having the tests do scaling, up/down of pods and such. we are targeting a release of a stable v1 of `onos-config` posting to precise versions of `test`,`topo` and `cli` by January 1st.

**Comment by adibrastegarnia** [comment]
@KramKroc 
Please reopen it, if you still have the issue but I think it is already addressed.
